package com.kevin.gestorproducao.automacao.motor;

public enum EstadoTela {
    SPLASH,
    LOGIN,
    NOTICIAS,
    SELECAO_PERSONAGEM,
    MUNDO_JOGO,
    MENU_ABERTO,
    MENU_PERSONAGEM,
    ARTESANATO_PRODUCOES_ATUAIS,
    ARTESANATO_LISTA_PROFISSOES,
    ARTESANATO_LISTA_TRABALHOS,
    CONFIRMACAO_INICIAR_PRODUCAO,
    DESCONHECIDA
}
